### PR TITLE
molecules update

### PR DESCRIPTION
**Pull request by hilburn**

### CODE REVIEW

**Comment by hilburn** [comment]
now with pictures

**Comment by jakimfett** [comment]
Yikes that's a lot of textures...is there any way we could calculate these on the fly? Or make the images smaller?

**Comment by way2muchnoise** [comment]
@jakimfett On the fly takes to much time and resources + it needs a lib to gen. And a resize might help mebe

**Comment by jakimfett** [comment]
Nevermind on the resize...it would only save about 100 bytes per image, for a total of less than 100kb saved, so probably not worth the time and effort.

**Pull request merged**
