### PR TITLE
Update fr_FR.lang

### PR DESCRIPTION
**Pull request by Mazdallier**
first translation.

### CODE REVIEW

**Comment by jakimfett** [comment]
At the end of the file, there's a few lines of English text. Did you have plans to translate them?

**Comment by Mazdallier** [comment]
of course and adding some text too...

**Comment by Mazdallier** [comment]
complet translation and begening of bonus.
Wants more ? tell me

**Comment by jakimfett** [comment]
Looks good, I'll go ahead and merge this.

**Pull request merged**
