### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by RAnders00**
This will appear whenever someone wants to create a issue as "please review the guidelines for reporting"

### CODE REVIEW

**Comment by way2muchnoise** [comment]
@RAnders00 What is the difference between this and our wiki page about it since it is copy pasta of it?

**Comment by RAnders00** [comment]
It's a copy pasta, but the wiki page does not appear as a warning when creating issues.
Without CONTRIBUTING.md:
Image loading...

With CONTRIBUTING.md:
Image loading...

**Comment by way2muchnoise** [comment]
:+1:

**Comment by jakimfett** [comment]
Wouldn't it make more sense to have the CONTRIBUTING.md contain a link to the appropriate wiki page(s), so that we're not maintaining multiple copies of the same document(s)?

**Comment by RAnders00** [comment]
I would actually prefer taking down the wiki page and just maintaining CONTRIBUTING.md

**Comment by jakimfett** [comment]
Whyso? Isn't the point of the wiki page to be...a wiki? Eg, there's multiple contribution types...eg, pull request, bug report, feature request...the CONTRIBUTING.md should point people in the correct direction for each of these, shouldn't it?

**Comment by RAnders00** [comment]
Since it's your project, feel free to do that.

**Comment by jakimfett** [comment]
Obviously I could do whatever I wanted, but I'm trying to understand the potential gains that moving instructions out of the wiki and into a flat file might give the project. I'm trying to evaluate the "why?" of this PR so I can make an informed decision on how to handle it (eg, approve, deny, modify, etc).

**Comment by RAnders00** [comment]
I wouldn't see a positive side of having the page on the Minechem wiki. I would rather update the wiki page to `Please head over to [the contributing guidelines](https://github.com/jakimfett/Minechem/blob/1.7.10-v6/CONTRIBUTING.md) to learn how to create issues.`

I would also expect a wiki contain purely game content. This is not to say meta content does not belong there but it would not be the place I would look if I wanted instrcutions on bug reporting. This is also why I would not expect many people to check out the wiki before reporting.

**Pull request closed without merging**
