### PR TITLE
adds achievement framework

### PR DESCRIPTION
**Pull request by way2muchnoise**
and a simple achievement for the journal

### CODE REVIEW

**Comment by hilburn** [comment]
@jakimfett do not accept

**Comment by way2muchnoise** [comment]
@jakimfett Do not merge yet the ASM is horribly broken, basically you can't open the achievements GUI anymore

**Comment by way2muchnoise** [comment]
To make it work in a dev env add ´´´´-Dfml.coreMods.load=minechem.asm.LoadingPlugin´´´´ to the VM arguments

**Comment by way2muchnoise** [comment]
@jakimfett This is now ready for merging. Should I solve the conflicts or are you going to? Also feel free to ask any questions.

**Comment by hilburn** [comment]
probably best if you solve the conflicts

**Comment by jakimfett** [comment]
Please do go ahead and resolve the merge conflicts @way2muchnoise. Also, does the VM argument need to be added for this to work right now? Or was that a temporary workaround?

**Comment by way2muchnoise** [comment]
@jakimfett The vm argument is only needed in dev env because forge needs to know that we ASM stuff. Included the needed things in the build.gradle

**Comment by jakimfett** [comment]
Awesome, thanks @way2muchnoise

**Comment by hilburn** [comment]
*Ahem*

**Pull request merged**
